---
services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester
      logging:
        level: "DEBUG"
  aws.greengrass.clientdevices.Auth:
    configuration:
      deviceGroups:
        formatVersion: "2021-03-05"
        definitions:
          myThing:
            selectionRule: "thingName:myThing"
            policyName: "thingAccessPolicy"
        policies:
          thingAccessPolicy:
            policyStatement1:
              statementDescription: "mqtt connect"
              effect: ALLOW
              operations:
                - "mqtt:connect"
              resources:
                - "mqtt:${iot:Connection.Thing.ThingName}:foo"
            policyStatement2:
              statementDescription: "mqtt publish"
              operations:
                - "mqtt:publish"
              resources:
                - "mqtt:topic:${iot:Connection.Thing.ThingName}"
  main:
    dependencies:
      - BrokerWithGetClientDeviceAuthTokenPermission
      - BrokerWithAuthorizeClientDeviceActionPermission
  BrokerWithGetClientDeviceAuthTokenPermission:
    dependencies:
      - aws.greengrass.clientdevices.Auth
    lifecycle:
      run:
        windows:
          powershell -command sleep 1
        posix:
          sleep 1
    configuration:
      accessControl:
        aws.greengrass.clientdevices.Auth:
          GetClientDeviceAuthTokenPolicy:
            policyDescription: access to certificate updates
            operations:
              - 'aws.greengrass#GetClientDeviceAuthToken'
            resources:
              - '*'
  BrokerWithAuthorizeClientDeviceActionPermission:
    dependencies:
      - aws.greengrass.clientdevices.Auth
    lifecycle:
      run:
        windows:
          powershell -command sleep 1
        posix:
          sleep 1
    configuration:
      accessControl:
        aws.greengrass.clientdevices.Auth:
          BrokerWithAuthorizeClientDeviceActionPermission:
            policyDescription: access to certificate updates
            operations:
              - 'aws.greengrass#AuthorizeClientDeviceAction'
            resources:
              - '*'
