---
services:
  aws.greengrass.Nucleus:
    configuration:
      runWithDefault:
        posixUser: nobody
        windowsUser: integ-tester
      logging:
        level: "DEBUG"
  aws.greengrass.clientdevices.Auth:
    configuration:
      deviceGroups:
        formatVersion: "2021-03-05"
        definitions:
          myThing:
            selectionRule: "thingName:myThing"
            policyName: "thingAccessPolicy"
        policies:
          thingAccessPolicy:
            connect:
              statementDescription: "mqtt connect"
              effect: ALLOW
              operations:
                - "mqtt:connect"
              resources:
                - "*"
            publish:
              statementDescription: "mqtt publish"
              operations:
                - "mqtt:publish"
              resources:
                - "mqtt:topic:my*ing"
            subscribe:
              statementDescription: "mqtt subscribe"
              operations:
                - "mqtt:subscribe"
              resources:
                - "mqtt:topic:*${iot:Connection.Thing.ThingName}*"
                # bad variable with wildcard
                - "mqtt:topic:*${iot:Connection.Thing.Thing.*Name}*"
  main:
    dependencies:
      - aws.greengrass.clientdevices.Auth
    configuration:
      accessControl:
        aws.greengrass.clientdevices.Auth:
          BrokerWithAuthorizeClientDeviceActionPermission:
            policyDescription: can authorize
            operations:
              - 'aws.greengrass#AuthorizeClientDeviceAction'
            resources:
              - '*'
