---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.certificate.manager
ComponentDescription: AWS Greengrass Certificate Manager
ComponentPublisher: AWS
ComponentVersion: 0.0.2
ComponentType: aws.greengrass.plugin
Manifests:
  - Parameters:
    - Name: devices
      Value: "[]"
      Type: STRING
    Artifacts:
      - URI: s3://gg-dev-artifacts/$componentName/$version/aws.greengrass.certificate.manager.jar
