/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.aws.greengrass.device.configuration.parser;

public
class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(RuleExpression p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c4dc0164775496b1fa090c39e5dbe05 (do not edit this line) */
