/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/* Generated By:JJTree: Do not edit this line. ASTThing.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.aws.greengrass.device.configuration.parser;

public
class ASTThing extends SimpleNode {
  public ASTThing(int id) {
    super(id);
  }

  public ASTThing(RuleExpression p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RuleExpressionVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be3d9bac3c767908aafa0e8cdacdf8b5 (do not edit this line) */
