/* Generated By:JJTree: Do not edit this line. ASTThing.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.aws.greengrass.device.configuration.parser;

public
class ASTThing extends SimpleNode {
  public ASTThing(int id) {
    super(id);
  }

  public ASTThing(RuleExpression p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19ec7d7f1200b2c66ab4650ab98d20bf (do not edit this line) */
