/* Generated By:JavaCC: Do not edit this line. RuleExpressionVisitor.java Version 7.0.10 */
package com.aws.greengrass.device.configuration.parser;

public interface RuleExpressionVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTThing node, Object data);
}
/* JavaCC - OriginalChecksum=b026344da0e8d4122005aeb45b3d9f0d (do not edit this line) */
