/* Generated By:JJTree&JavaCC: Do not edit this line. RuleExpressionConstants.java */
/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package com.aws.greengrass.clientdevices.auth.configuration.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RuleExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OR = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int THINGNAME = 6;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"OR\"",
    "\"AND\"",
    "<THINGNAME>",
    "<ALPHANUMERIC>",
    "\"thingName:\"",
  };

}
