/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/* Generated By:JavaCC: Do not edit this line. RuleExpressionTreeConstants.java Version 7.0.10 */
package com.aws.greengrass.clientdevices.auth.configuration.parser;

public interface RuleExpressionTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTTHING = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Or",
    "And",
    "Thing",
  };
}
/* JavaCC - OriginalChecksum=be39e2ea755df5f713cf8bf594306e43 (do not edit this line) */
