name: Benchmarks

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
          cache: maven
      - name: Run Benchmarks
        run: ./run-benchmarks.sh
        working-directory: ./benchmark
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: Benchmark Results
          path: ./benchmark/jmh-result.json
      - name: Comment With Results
        uses: actions/github-script@v7
        env:
          RESULTS_FILE: ./benchmark/jmh-result.json
        with:
          script: |
            const postBenchmarkComment = require('./.github/scripts/benchmark-comment.js');
            await postBenchmarkComment({github, context, core});
