name: Java CI UAT

on:
  push:
    branches:
      - main
      - uat-dev
  pull_request:
    branches: '**'

jobs:
  build:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        if: matrix.os == 'ubuntu-latest'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        working-directory: uat
        run: mvn -ntp -U clean verify
        if: matrix.os != 'windows-latest'
