#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > /tmp/greengrass-nucleus-latest.zip
      - mvn -DskipTests=false -U -ntp clean verify -f uat/pom.xml
      - sudo -E java -Dggc.archive=/tmp/greengrass-nucleus-latest.zip -Dtags=GGMQ -jar uat/testing-features/target/client-devices-auth-testing-features.jar

artifacts:
  files:
    - 'testResults/**/*'
  name: 'AuthUatLinuxLogs.zip'

reports:
  uat-reports:
    files:
      - "TEST-greengrass-results.xml"
    file-format: "JUNITXML"

cache:
  paths:
    - '/root/.m2/**/*'
