#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 0.2
env:
  variables:
    CUCUMBER_TAGS: '@GGMQ'
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > /tmp/greengrass-nucleus-latest.zip
      - mvn -U -DskipTests -ntp clean verify -f uat/pom.xml
      - java -Dggc.archive=/tmp/greengrass-nucleus-latest.zip -Dtags="$CUCUMBER_TAGS" -jar uat/testing-features/target/client-devices-auth-testing-features.jar 2>&1 | tee build.log

artifacts:
  files:
    - 'testResults/**/*'
    - 'build.log'
  name: 'AuthUatLinuxLogs.zip'

reports:
  uat-reports:
    files:
      - "TEST-greengrass-results.xml"
    file-format: "JUNITXML"
  uat-cucumber-reports:
    files:
      - "testResults/cucumber.json"
    file-format: "CUCUMBERJSON"

cache:
  paths:
    - '/root/.m2/**/*'
